[book]
authors = ["Vasanthadithya Mundrathi from CBIT college"]
language = "en"
multilingual = false
src = "src"
title = "ChainCraft Node Specification"

[output.html]
# Removed GitHub repository URL for local development

[preprocessor.toc]
command = "mdbook-toc"
renderer = ["html"]
